### ISSUE TITLE
leapfrogai serve fails to stop gracefully

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai-sdk#4]
There seems to be an issue, both in Docker and my host environment (Python 3.11.6 or Python 3.10.2 in a VENV, Ubuntu 22.04.3 LTS), where using "Ctrl-C" (SIGINT) to end the process in the terminal causes `leapfrogai.serve()` to crash the server and hang instead of stopping gracefully. On the host environment (developer mode with just `python main.py`), this is fine since one can just press "Ctrl-C" a 2nd time to kill the hanging process; however if running via Docker without detached mode, the terminal will hang as well, causing the user to open another terminal to kill the Docker container.

Below are the logs, which are the same/similar for CTransformers' backend as well:
```bash
(.venv) jlaw@law-desktop ➜  ~/dev/leapfrogai-backend-whisper git:(add-gpu-support) ~ python main.py 
Initializing Leapfrog
Starting server. Listening on port 50051.
^CTraceback (most recent call last):
  File "/home/jlaw/dev/leapfrogai-backend-whisper/main.py", line 87, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Exception ignored in: <function Server.__del__ at 0x7f5b00a441f0>
Traceback (most recent call last):
  File "/home/jlaw/dev/leapfrogai-backend-whisper/.venv/lib/python3.10/site-packages/grpc/aio/_server.py", line 185, in __del__
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/common.pyx.pxi", line 118, in grpc._cython.cygrpc.schedule_coro_threadsafe
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/common.pyx.pxi", line 110, in grpc._cython.cygrpc.schedule_coro_threadsafe
  File "/usr/lib/python3.10/asyncio/base_events.py", line 436, in create_task
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'AioServer.shutdown' was never awaited
```

**Comment by justinthelaw** [comment]
The installed package's code for `leapfrogai.serve` is below:

```python
from concurrent import futures
import grpc

from grpc_health.v1 import health
from grpc_health.v1 import health_pb2
from grpc_health.v1 import health_pb2_grpc

from grpc_reflection.v1alpha import reflection

from .audio import audio_pb2_grpc
from .chat import chat_pb2_grpc
from .embeddings import embeddings_pb2_grpc
from .completion import completion_pb2_grpc
from .name import name_pb2_grpc


async def serve(o):
    # Create a tuple of all of the services we want to export via reflection.
    services = (reflection.SERVICE_NAME, health.SERVICE_NAME)

    # Create a gRPC server
    server = grpc.aio.server(futures.ThreadPoolExecutor(max_workers=40))

    if hasattr(o, "ChatComplete"):
        chat_pb2_grpc.add_ChatCompletionServiceServicer_to_server(o, server)
        services += ("chat.ChatCompletionService",)

    if hasattr(o, "ChatCompleteStream"):
        chat_pb2_grpc.add_ChatCompletionStreamServiceServicer_to_server(o, server)
        services += ("chat.ChatCompletionStreamService",)

    if hasattr(o, "Complete"):
        completion_pb2_grpc.add_CompletionServiceServicer_to_server(o, server)
        services += ("completion.CompletionService",)

    if hasattr(o, "CompleteStream"):
        completion_pb2_grpc.add_CompletionStreamServiceServicer_to_server(o, server)
        services += ("completion.CompletionStreamService",)

    if hasattr(o, "CreateEmbedding"):
        embeddings_pb2_grpc.add_EmbeddingsServiceServicer_to_server(o, server)
        services += ("embeddings.EmbeddingsService",)

    if hasattr(o, "Name"):
        name_pb2_grpc.add_NameServiceServicer_to_server(o, server)
        services += ("name.NameService",)

    if hasattr(o, "Transcribe") and hasattr(o, "Translate"):
        audio_pb2_grpc.add_AudioServicer_to_server(o, server)
        services += ("audio.Audio",)

    # Do reflection things to list all the gRPC services (allows for `grpcurl --plaintext localhost:50051 list`)
    reflection.enable_server_reflection(services, server)

    # Create a health_servicer and list all services as 'healthy'
    # NOTE: Health checks can be validated via `grpcurl --plaintext -d {"service": "SERVICE_NAME"}' localhost:50051 grpc.health.v1.Health/Check`
    health_servicer = health.HealthServicer(experimental_non_blocking=True)
    health_pb2_grpc.add_HealthServicer_to_server(health_servicer, server)
    for service in services:
        # TODO: I still need to modify the protos for the services to add a 'check' endpoint
        health_servicer.set(service, health_pb2.HealthCheckResponse.SERVING)

    # Listen on port 50051
    print("Starting server. Listening on port 50051.")
    server.add_insecure_port("[::]:50051")
    await server.start()

    # block the thread until the server terminates...without using async to await the completion
    # of all requests, this is the best we can do to gracefully wait while the server responds to requests
    await server.wait_for_termination()

```

**Comment by gerred** [comment]
The fix is on main: https://github.com/defenseunicorns/leapfrogai-sdk/blob/main/src/leapfrogai/serve.py#L67-L83 but the ctransformers backend isn't on 0.4.0 yet, once it is that will fix this.
